### ISSUE TITLE
Installation section with wrong content

### ISSUE THREAD

**Issue by juan-morales** [phalcon/zephir-docs#228]
The **installation** section in the documentation is showing the content/steps used in version 0.10 instead 0.12

I think is a bug in the site and maybe another sections in the documentation too

**Comment by sergeyklay** [comment]
@juancarmo Do you mean `/0.12/en/installation`? Could you please check again.

**Comment by sergeyklay** [comment]
Thank you for the report! We'll deploy the fix ASAP.

**Comment by sergeyklay** [comment]
@juancarmo Just deployed the fix
