### ISSUE TITLE
Proposal: Choice a better font name / family for documentation

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/zephir-docs#351]
IMO current font face looks not so pretty. I propose change font family to sans.

![zephir-docs-font-face](https://user-images.githubusercontent.com/1256298/78607140-2f5fe600-7867-11ea-8d74-6b2bb3d66e16.png)

/cc @Arhell

**Comment by Arhell** [comment]
Hi @sergeyklay 
https://fonts.google.com/specimen/Open+Sans?query=sans ?

**Comment by sergeyklay** [comment]
@Arhell Yes, Open Sans looks better.

**Comment by Arhell** [comment]
@sergeyklay  Or maybe try
https://fonts.google.com/specimen/Titillium+Web?query=tit ??

**Comment by sergeyklay** [comment]
We should choose a font with multilingual support to provide wide range of supported chars

**Comment by Arhell** [comment]
resolve
