### ISSUE TITLE
Ru: Motivation

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/zephir-docs#68]
@rigin 

Кажется, тут 2 идентичных блока
https://docs.zephir-lang.com/ru/latest/motivation.html#conclusion

> Защита кода¶
> В некоторых случаях компиляция не приводит к существенному повышению производительности, это может быть связано с тем, что узкое место расположено в области ввода-вывода приложения (что вполне вероятно), а не в вычислении/памяти. Тем не менее, компиляция кода может также обеспечить определенный уровень интеллектуальной защиты для вашего приложения. Благодаря Zephir, производящему конечные двоичные файлы, вы также получаете возможность скрывать код для пользователей или клиентов.

и

> Заключение¶
> В некоторых случаях компиляция не приводит к существенному повышению производительности, это может быть связано с тем, что узкое место расположено в области ввода-вывода приложения (что вполне вероятно), а не в вычислении/памяти. Тем не менее, компиляция кода может также обеспечить определенный уровень интеллектуальной защиты для вашего приложения. Благодаря Zephir, производящему конечные двоичные файлы, вы также получаете возможность скрывать код для пользователей или клиентов.

**Comment by rigin** [comment]
Поправил.
Сергей, вы мануал в pdf файл не сгенерируете?
А то он на английском сейчас.

**Comment by sergeyklay** [comment]
Да, чуть позже, при деплое
