### ISSUE TITLE
Missing Optimizations docs

### ISSUE THREAD

**Issue by flyingangel** [phalcon/zephir-docs#74]
In config.json of zephir compiler, there are 2 non documented optimizations :
- check-invalid-reads
- internal-call-transformation

Also because now it uses the json file, command in the documentation such as `zephir -fstatic-type-inference` no longer work

**Comment by niden** [comment]
Added some text for the `check-invalid-reads`.

Need to check with @sergeyklay for the other two so that we can correct the documents.

@flyingangel thank you for reporting this!

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/zephir-docs/pull/137
