### ISSUE TITLE
Remove Chinese and Russian version

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/zephir-docs#81]
It's not scalable to require a translation of it every time we make changes to the primary documentation, which is in English. If we want to keep it we move it to a separate repository and make sure there is a clear maintainer for it.

/cc @phalcon/zephir-team

**Comment by danhunsaker** [comment]
I'm with @niden on this one - I'd rather have translations than not, but the current way isn't, as you point out, working. I believe I said something to this effect once before, though maybe I was just thinking it at the time.

**Comment by sergeyklay** [comment]
@niden Could you please start this work?

**Comment by niden** [comment]
This has been addressed. All documentation is now in markdown format and handled by our friends at Crowdin (https://crowdin.com)

The project is located here: https://crowdin.com/project/zephir-documentation
